version: '3.8'
services:

  booking:
    build: ./
    container_name: app
    command: ./booking
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:alpine
    restart: always
    container_name: db
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
