version: '3.8'
services:
  db:
    image: postgres:alpine
    restart: always
    container_name: db
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
